name: screenshot

on:
  schedule:
    - cron: "*/5 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: ${{ secrets.MAIN_PAGE }}
          output: main.png

      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: ${{ secrets.ADMIN_PAGE }}
          output: admin.png

      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: ${{ secrets.CATEGORY_PAGE }}
          output: category.png

      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: ${{ secrets.PRODUCT_PAGE }}
          output: product.png
     
      - name: send Screenshot Main Page
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: '#main_page'
          photo: ${{ github.workspace }}/main.png

      - name: send Screenshot Admin Page
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: '#admin_page'
          photo: ${{ github.workspace }}/admin.png

      - name: send Screenshot Category Page
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: '#category_page'
          photo: ${{ github.workspace }}/category.png

      - name: send Screenshot Product Page
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: '#product_page'
          photo: ${{ github.workspace }}/product.png
